excludeLinksFromLockfile: true

allowBuilds:
  mongodb-memory-server: set this to true or false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - gambling-bot-shared
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
