allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - gambling-bot-shared
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  gambling-bot-shared: link:../gambling-bot-shared
