export { default as HomePage } from './general/home/HomePage'
export { default as TransactionsPage } from './general/transactions/TransactionsPage'
export { default as ChannelSettingsPage } from './settings/channels/ChannelSettingsPage'
export { default as UsersPage } from './manage//users/UsersPage'
export { default as CasinoSettingsPage } from './settings/casino/CasinoSettingsPage'
export { default as ManagerSettingsPage } from './settings/manager-role/ManagerSettingsPage'
export { default as VipSettingsPage } from './settings/vip/VipSettingsPage'
export { default as BonusesSettingsPage } from './settings/bonuses/BonusesSettingsPage'
